name: deploy flask project to vps

# Hello world! Run this to push

on: push


jobs:
  run-tests:
    runs-on: ubuntu-20.04
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests with Pytest
        run: pytest
  
  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Deploy Flask app 
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}} 
       #   key: ${{secrets.SSH_KEY}}
        #  passphrase: ${{ secrets.SSH_PASS }}
          script: |
            echo 'Checkout test'
            cd /home/power
            git pull
            echo 'Check change'
            cd
            systemctl restart lib
            echo 'Restart complete'